server:
  port: 9090
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: pizza-order-service
  datasource:
    url: ${POSTGRES_CONNECTION_STRING:jdbc:postgresql://localhost:5431/postgres}
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active:
      - default

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
